name: Test
on: push 

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Runs Django Tests
      run: |
        pip3 install -r requirements.txt
        cd cinephiles
        python manage.py test 